spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://root:example@localhost:27017/JobOffers-web?authSource=admin
  task:
    scheduling:
      enabled: false

offers:
  http:
    client:
      config:
        uri: http://ec2-3-127-218-34.eu-central-1.compute.amazonaws.com
        port: 5057
        readTimeout: 1000
  scheduler:
    request:
      delay: "*/10 * * * * *"
