spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://root:example@localhost:27017/JobOffers-web?authSource=admin
  task:
    scheduling:
      enabled: false

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:63792}
  cache:
    type: redis
    redis:
      time-to-live: PT10S

offers:
  http:
    client:
      config:
        uri: http://ec2-18-194-181-208.eu-central-1.compute.amazonaws.com
        port: 5057
  scheduler:
    request:
      delay: "*/10 * * * * *"

auth:
  jwt:
    secret: ${JWT_SECRET}
    expiration-days: 30
    issuer: Job Offers Service